### PR TITLE
Fix version property for camel-maven-plugin

### PR DESCRIPTION
**Pull request by mcarlett**

### CODE REVIEW

**Review by Croway — APPROVED** [review]

**Review by cunningt — COMMENTED** [review]
This should be the ${camel-community-version} - we don't productize camel-maven-plugin.

https://orch.psi.redhat.com/pnc-web/#/projects/28/build-configs/9166/builds/AXMRBCHMGSYAC/artifacts

**Comment by mcarlett** [comment]
> This should be the ${camel-community-version} - we don't productize camel-maven-plugin

thanks @cunningt ! should I use the community version in any other pom.xml ? I see we used always `${camel-version}`

**Comment by cunningt** [comment]
We use ${camel-community.version} in a lot of places in camel-spring-boot, it's really a question of whether the artifact is productized in camel - I think there are two ways to check whether an artifact is being productized

- PNC (link to current camel build : https://orch.psi.redhat.com/pnc-web/#/projects/28/build-configs/9166/builds/AXMRBCHMGSYAC ), click artifacts, and then check whether the artifact was built by searching for the artifact within the build.     
- or look at the .mvn/excludes.txt for camel https://github.com/jboss-fuse/camel/blob/camel-3.20.1-branch/.mvn/excludes.txt - this file gets generated by the plugin and is the set of modules that is excluded / commented out from the build because we are not productizing them

**Comment by cunningt** [comment]
> This should be the ${camel-community-version} - we don't productize camel-maven-plugin.
> 
> https://orch.psi.redhat.com/pnc-web/#/projects/28/build-configs/9166/builds/AXMRBCHMGSYAC/artifacts

Made a mistake here - it's ${camel-community.version} (there's a dot between community and version) 
https://github.com/jboss-fuse/camel-spring-boot/blob/camel-spring-boot-3.20.1-branch/pom.xml#L122

**Comment by mcarlett** [comment]
I replaced the `camel.version` with `camel-community.version` since it is resolved in example parent (`<groupId>org.apache.camel.springboot.example</groupId>`) -> spring-boot (`<artifactId>spring-boot</artifactId>`)

**Pull request merged**
